name: learn-github-actions
run-name: ${{ github.actor }} is learning github actions
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i @angular/cli
      - run: npm install
      - run: npm run build
      - run: sudo apt install openssh-server
      - run: sudo apt install openssh-server
      - run: ssh vps53057@191.252.113.54
      - run: root
      - run: Quartamarcha@4
