on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  connect_locaweb_server:
    name: connect_locaweb_server
    runs-on: ubuntu-latest
    steps:
      - run: apt install openssh-server

