on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  connect_locaweb_server:
    name: connect_locaweb_server
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install openssh-server
      - run: ssh vps53057@191.252.113.54


